export const employees = [
  {
    id: 1,
    fname: "Rufus Sam John Immanvel",
    lname: "J",
    email: "rsamjohnimmanvelj@deloitte.com",
    phno: "8877889988",
    desig: "Level2",
    isAdmin: false,
  },
  {
    id: 2,
    fname: "Shreesh",
    lname: "Lahauriya",
    email: "shreeshlahauriya@deloitte.com",
    phno: "9922334455",
    desig: "Level22",
    isAdmin: true,
  },
  {
    id: 3,
    fname: "Shreesh",
    lname: "Lahauriya",
    email: "shreeshlahauriya@deloitte.com",
    phno: "9922334455",
    desig: "Level22",
    isAdmin: true,
  },
  {
    id: 4,
    fname: "Shreesh",
    lname: "Lahauriya",
    email: "shreeshlahauriya@deloitte.com",
    phno: "9922334455",
    desig: "Level22",
    isAdmin: true,
  },
  {
    id: 5,
    fname: "Rufus Sam John Immanvel",
    lname: "J",
    email: "rsamjohnimmanvelj@deloitte.com",
    phno: "8877889988",
    desig: "Level2",
    isAdmin: false,
  },
  {
    id: 6,
    fname: "Rufus Sam John Immanvel",
    lname: "J",
    email: "rsamjohnimmanvelj@deloitte.com",
    phno: "8877889988",
    desig: "Level2",
    isAdmin: false,
  },
  {
    id: 7,
    fname: "Bhaskar",
    lname: "Gonugunta",
    email: "bhaskargonugunta@deloitte.com",
    phno: "3456789011",
    desig: "Level7",
    isAdmin: false,
  },
  {
    id: 8,
    fname: "Bhaskar",
    lname: "Gonugunta",
    email: "bhaskargonugunta@deloitte.com",
    phno: "3456789011",
    desig: "Level7",
    isAdmin: false,
  },
  {
    id: 9,
    fname: "Bhaskar",
    lname: "Gonugunta",
    email: "bhaskargonugunta@deloitte.com",
    phno: "3456789011",
    desig: "Level7",
    isAdmin: false,
  },
  {
    id: 10,
    fname: "Rufus Sam John Immanvel",
    lname: "J",
    email: "rsamjohnimmanvelj@deloitte.com",
    phno: "8877889988",
    desig: "Level2",
    isAdmin: false,
  },
  {
    id: 11,
    fname: "Rufus Sam John Immanvel",
    lname: "J",
    email: "rsamjohnimmanvelj@deloitte.com",
    phno: "8877889988",
    desig: "Level2",
    isAdmin: false,
  },
  {
    id: 12,
    fname: "Bhaskar",
    lname: "Gonugunta",
    email: "bhaskargonugunta@deloitte.com",
    phno: "3456789011",
    desig: "Level7",
    isAdmin: false,
  },
  {
    id: 13,
    fname: "Bhaskar",
    lname: "Gonugunta",
    email: "bhaskargonugunta@deloitte.com",
    phno: "3456789011",
    desig: "Level7",
    isAdmin: false,
  },
  {
    id: 14,
    fname: "Bhaskar",
    lname: "Gonugunta",
    email: "bhaskargonugunta@deloitte.com",
    phno: "3456789011",
    desig: "Level7",
    isAdmin: false,
  },
  {
    id: 15,
    fname: "Bhaskar",
    lname: "Gonugunta",
    email: "bhaskargonugunta@deloitte.com",
    phno: "3456789011",
    desig: "Level7",
    isAdmin: false,
  },
  {
    id: 16,
    fname: "Mithun",
    lname: "P",
    email: "mithup@deloitte.com",
    phno: "3456789011",
    desig: "Level7",
    isAdmin: false,
  },
];
